version: 2
jobs:
  build:
    machine: true
    environment:
      CORE_NAME: mycore
      SOLR_CONTAINER_NAME: solr_container
      SOLR_PORT: 8983
    steps:
      - checkout
      - run:
          name: Create Solr container with a core named "mycore"
          command: |
            set -x
            docker-compose up -d
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for Solr
          command: dockerize -wait http://localhost:$SOLR_PORT -timeout 1m
      - run:
          name: Load test data into Solr
          command: |
            set -x
            # Wait for Solr core to load
            sleep 15
            docker exec -it --user=solr $SOLR_CONTAINER_NAME bin/post -c $CORE_NAME example/exampledocs/manufacturers.xml
      - run:
          name: Test Solr
          command: |
            set -x
            sleep 10
            data=$(docker exec -it --user=solr $SOLR_CONTAINER_NAME wget -q -O - 'http://localhost:$SOLR_PORT/solr/$CORE_NAME/select?q=id%3Adell')
            echo $data
            if ! egrep -q 'Texas' <<<$data; then
              echo "An error occurred; data did not load"
              exit 1
            fi

