version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Create Solr container with a core named "mycore"
          command: |
            set -x
            docker-compose up -d
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for Solr
          command: dockerize -wait http://localhost:8983 -timeout 1m
      - run:
          name: Load test data into Solr
          command: |
            # Wait for Solr core to load
            sleep 60
            docker exec -it --user=solr solr_container bin/post -c mycore example/exampledocs/manufacturers.xml
      - run:
          name: Test Solr
          command: |
            sleep 10
            data=$(docker exec -it --user=solr solr_container wget -q -0 - 'http://localhost:8983/solr/gettingstarted/select?q=id%3Adell')
            if ! egrep -q 'One Dell Way Round Rock, Texas 78682' <<<$data; then
              echo "An error occurred; data did not load"
              exit 1
            fi

