version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Create Solr container with a core named "mycore"
          command: |
            set -x
            docker-compose up -d
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for Solr
          command: dockerize -wait tcp://localhost:8983 -timeout 1m
      - run:
          name: Load test data into Solr
          command: |
            set -x
            docker exec -it --user=solr solr_container bin/post -c mycore example/exampledocs/manufacturers.xml
